### ISSUE TITLE
Different results on `StructuralIdentifiability` and `SIAN`

### ISSUE THREAD

**Issue by amostof** [SciML/StructuralIdentifiability.jl#122]
Hello,
When I run this system of ODEs on `StructuralIdentifiability` vs `SIAN`, I get different results,
```
solver = :SIAN

if solver == :StructuralIdentifiability
    using StructuralIdentifiability
elseif solver == :SIAN
    using SIAN
end

ode = @ODEmodel(
    n'(t) = (co(t)/(co(t)+Ko)) * (cg(t)/(cg(t)+Kg)) * (Kl/(cl(t)+Kl)) * beta * n(t) * (1-n(t)/nmax) - delta * n(t),
    co'(t) = 0,
    cg'(t) = -Vg * n(t) * (cg(t) / (cg(t) + cbarg)),
    cl'(t) = - 2 * (-Vo * n(t) * (co(t) / (co(t) + cbaro))) + (-Vg * n(t) * (cg(t) / (cg(t) + cbaro)))/3,
    y1(t) = n(t),
    y2(t) = cg(t),
    y3(t) = cl(t),
    y4(t) = co(t)
)

if solver == :StructuralIdentifiability
    output = assess_identifiability(ode, 0.99)
elseif solver == :SIAN
    output_single = identifiability_ode(ode, get_parameters(ode; initial_conditions=false); p=0.99)
end
```

I assumed that the reason might be because `StructuralIdentifiability` assumes the initial conditions to be known while `SIAN` assumes them to be unknown. Is there a way for me to set the initial conditions to know/unknown on either package?

**Comment by pogudingleb** [comment]
@amostof 
Thank you for contacting us and for a very interesting example!

In fact, both tools assume that the initial conditions are unknown (the colleagues are working on adding a feature of known generic initial conditions to `SIAN`).

The reason for the discrepancy you have observed is that `SIAN` assesses *single-experiment* identifiability, that is, whether observing one trajectory is enough to determine the parameter values, while `StructuralIdentifiability` checks *mulit-experiment* identifiability, that is, which of the parameters can be inferred if you are allowed to conduct several experiments with different initial conditions.

In the majority of the cases, these two notions coincide, so the tools give the same result. In your case, they do not, and `StructuralIdentifiability` throws a warning:
```
Warning: One of the Wronskians has corank greater than one, so the results of the algorithm will be valid only for multiexperiment identifiability. 
If you still  would like to assess single-experiment identifiability, we recommend using SIAN (https://github.com/alexeyovchinnikov/SIAN-Julia)
```
In almost all the cases when this discrepancy occurs, it is due to having states with constant dynamic such as `co(t)` in your case. If you recast it as a parameter, so if you rewrite your systems as follows:
```julia
ode = @ODEmodel(
    n'(t) = (co/(co+Ko)) * (cg(t)/(cg(t)+Kg)) * (Kl/(cl(t)+Kl)) * beta * n(t) * (1-n(t)/nmax) - delta * n(t),
    cg'(t) = -Vg * n(t) * (cg(t) / (cg(t) + cbarg)),
    cl'(t) = - 2 * (-Vo * n(t) * (co / (co + cbaro))) + (-Vg * n(t) * (cg(t) / (cg(t) + cbaro)))/3,
    y1(t) = n(t),
    y2(t) = cg(t),
    y3(t) = cl(t),
    y4(t) = co
)
```
single- and multi-experimental setups will coincide, and both tools will give you the same result.

Let me know if you have any further questions.

**Comment by amostof** [comment]
Thanks for the prompt and clear response. That solves my problem. I do have another question. In the main README.md file
we have, 
> `u(t)` is the input/control variable which is assumed to be known and generic (exciting) enough;

What does this generic enough condition mean and is it applicable here for `co`?

**Comment by pogudingleb** [comment]
@amostof 
Input function is a function which appears only on the right-hand side, you can think of it as an external force imposed by an experimenter (or, say, drug injection). Genericity means that it is nonconstant enough to nontrivially perturb the system.
If I understand correctly, your `co` is constrained to have constant dynamics, so it cannot be viewed as an exciting input.

**Comment by amostof** [comment]
I see. But setting `co` equal to a constant as you mentioned via `y4(t) = co`, means that `co` is constrained to have constant dynamics, and would mean that structural identifiability will be granted with only one experiment. Right?

**Comment by pogudingleb** [comment]
Setting `y4(t) = co` indeed means that `co` is constrained to be a constant, and the result of identifiability analysis (with two parameters being nonidentifiable) will correspond to a single experiment.
I hope this answers your question.

**Comment by amostof** [comment]
Yes it does. Thanks for all the help.
