### ISSUE TITLE
Check Structural Identifiability with some fixed parameters

### ISSUE THREAD

**Issue by Mehdilotfi7** [SciML/StructuralIdentifiability.jl#123]
I am using StructuralIdentifiability.jl package to check the Identifiability of ODE by fixing some model parameters. The model includes seven variable states and 22 parameters, of which 12 are fixed. (I defined fixed parameters by param_values as Dict.)
I have googled it and found nothing more except using StructuralIdentifiability.set_parameter_values(ode, param_values) function, but when I use it and define param_values by param_values = Dict(ηψᵥ=>19.03,γc=>1.31,ψₛ=>410e-3,ξ=>510e-9,
μₛ=>0.14,μᵢ=>0.15,ψᵣ=>0.02,αᵣ=>0.001,μᵣ=>0.02,
κ=>0.05,μₐ=>0.02,νₐ=>0.07
)
, face the following error: Any suggestion or other solutions??
MethodError: no method matching set_parameter_values(::ODE{Nemo.fmpq_mpoly}, ::Dict{Nemo.fmpq_mpoly, Float64})
Closest candidates are:
set_parameter_values(::ODE{P}, ::Dict{P, T}) where {T<:AbstractAlgebra.FieldElem, P<:AbstractAlgebra.MPolyElem{T}} at ~/.julia/packages/StructuralIdentifiability/ooOlO/src/ODE.jl:62

**Comment by pogudingleb** [comment]
@Mehdilotfi7 
Yes, you can use `set_parameter_values`, the reason why you are getting this error is that it expects rational numbers, not floats. So for now you can pass the numbers as rationals, say `QQ(1903, 100)` instead of `19.03`. You can use this [example](https://github.com/SciML/StructuralIdentifiability.jl/blob/master/examples/NFkB.jl) as a template.

Thank you for brining up this issue, we will add a function which would able to take floats and convert them to rationals internally.

Let us know if you have any further questions.

**Comment by Mehdilotfi7** [comment]
Thank you for your nice response, it worked.
I think your mentioned notation about conversion is a good idea.

**Comment by pogudingleb** [comment]
@Mehdilotfi7 
The feature with using floats in `set_parameter_values` is available in the current version on GitHub and will be included into the next release. Thank you again for bringing it up!
