### ISSUE TITLE
Replacing `GroebnerBasis` with `msolve`

### ISSUE THREAD

**Issue by pogudingleb** [SciML/StructuralIdentifiability.jl#55]
`GroebnerBasis.jl` is now depreciated, so it would be great to move the code to `msolve`. At the moment, F4 works only over finite fields, so one should either
 - refine the sampling bound from the paper (Theorem 3.3 in https://arxiv.org/abs/2111.00991)
 - reduce to the zero-dimensional solving

**Comment by finmod** [comment]
The latest update to v0.3.5 does not solve this issue.

**Comment by pogudingleb** [comment]
@finmod This is correct.
Note that, the used functionality of `GroebnerBasis.jl` is not completely supported by `msolve`, this makes the transition not straightforward.

**Comment by iliailmer** [comment]
Right now I tried to make it work with `FiniteField` but it has not worked yet due to this error: https://github.com/SciML/StructuralIdentifiability.jl/runs/4762906264?check_suite_focus=true#step:5:989. I have not figured it out yet, I think it comes from some Nemo functionality. Also, once `msolve` works with characteristic 0, the transition should be simplified, so another solution is to wait 😃

**Comment by pogudingleb** [comment]
`GroebnerBases.jl` has been replaced by `Groebner.jl` and it works fine. It would be still a good idea to have solve as an additional backend, I will open a separate issue for this.

**Comment by finmod** [comment]
test StructuralIdentifiability is now compiling and passing ok,
